# Generated by Django 3.1.7 on 2021-02-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
    ]
